export const STAPLE_QUERIES = [
  "chicken breast",
  "ground turkey",
  "eggs",
  "greek yogurt",
  "tofu",
  "salmon",
  "tuna",
  "rice",
  "potatoes",
  "oats",
  "whole wheat bread",
  "tortillas",
  "beans",
  "lentils",
  "broccoli",
  "spinach",
  "bananas",
  "berries",
  "olive oil",
  "avocado",
  "peanut butter",
  "protein powder",
];

export const MOCK_STORES = [
  {
    provider: "google_places",
    providerPlaceId: "mock-ralphs-1",
    name: "Ralphs Market",
    formattedAddress: "123 Main St, Los Angeles, CA",
    lat: 34.0522,
    lng: -118.2437,
    placeTypes: ["grocery_store", "food", "store"],
    chain: "Kroger",
    distanceMiles: 1.2,
    supportsInventoryLookup: true,
    inventoryProvider: "kroger",
  },
  {
    provider: "google_places",
    providerPlaceId: "mock-trader-joes-1",
    name: "Trader Joe's",
    formattedAddress: "456 Oak Ave, Los Angeles, CA",
    lat: 34.061,
    lng: -118.255,
    placeTypes: ["grocery_store", "food", "store"],
    chain: "Trader Joe's",
    distanceMiles: 2.4,
    supportsInventoryLookup: false,
    inventoryProvider: "none",
  },
  {
    provider: "osm",
    providerPlaceId: "mock-neighborhood-market-1",
    name: "Neighborhood Fresh Market",
    formattedAddress: "88 Hill St, Los Angeles, CA",
    lat: 34.047,
    lng: -118.25,
    placeTypes: ["supermarket"],
    chain: "Independent",
    distanceMiles: 3.1,
    supportsInventoryLookup: true,
    inventoryProvider: "manual",
  },
  {
    provider: "google_places",
    providerPlaceId: "mock-sprouts-1",
    name: "Sprouts Farmers Market",
    formattedAddress: "912 Sunset Blvd, Los Angeles, CA",
    lat: 34.07,
    lng: -118.27,
    placeTypes: ["grocery_store", "health_food_store"],
    chain: "Sprouts",
    distanceMiles: 4.6,
    supportsInventoryLookup: false,
    inventoryProvider: "none",
  },
];

export const MOCK_PRODUCTS = [
  product("chicken", "Kroger Boneless Skinless Chicken Breast", "meat", 499, "1 lb", true, ["chicken breast"]),
  product("turkey", "93 Percent Lean Ground Turkey", "meat", 599, "1 lb", true, ["ground turkey"]),
  product("eggs", "Large Eggs", "eggs", 429, "12 ct", true, ["eggs"]),
  product("greek_yogurt", "Plain Nonfat Greek Yogurt", "greek_yogurt", 549, "32 oz", true, ["greek yogurt"]),
  product("tofu", "Extra Firm Tofu", "tofu", 249, "14 oz", true, ["tofu"]),
  product("salmon", "Atlantic Salmon Fillet", "fish", 1099, "1 lb", "unknown", ["salmon"]),
  product("tuna", "Chunk Light Tuna Pouches", "fish", 149, "2.6 oz", true, ["tuna"]),
  product("rice", "Long Grain White Rice", "rice", 699, "5 lb", true, ["rice"]),
  product("potatoes", "Russet Potatoes", "potatoes", 399, "5 lb", true, ["potatoes"]),
  product("oats", "Old Fashioned Oats", "oats", 449, "42 oz", true, ["oats"]),
  product("bread", "Whole Wheat Bread", "bread", 399, "20 oz", true, ["whole wheat bread"]),
  product("tortillas", "Whole Wheat Tortillas", "tortillas", 379, "10 ct", true, ["tortillas"]),
  product("beans", "Black Beans", "beans", 139, "15 oz", true, ["beans"]),
  product("lentils", "Dry Lentils", "lentils", 229, "1 lb", true, ["lentils"]),
  product("broccoli", "Frozen Broccoli Florets", "broccoli", 249, "12 oz", true, ["broccoli"]),
  product("spinach", "Baby Spinach", "spinach", 349, "5 oz", true, ["spinach"]),
  product("banana", "Bananas", "banana", 79, "1 lb", true, ["bananas"]),
  product("berries", "Frozen Mixed Berries", "berries", 599, "16 oz", true, ["berries"]),
  product("olive_oil", "Extra Virgin Olive Oil", "olive_oil", 899, "16.9 oz", true, ["olive oil"]),
  product("avocado", "Hass Avocado", "avocado", 125, "1 ct", "unknown", ["avocado"]),
  product("peanut_butter", "Natural Peanut Butter", "peanut_butter", 399, "16 oz", true, ["peanut butter"]),
  product("protein_powder", "Plant Protein Powder", "protein_powder", 2499, "1.5 lb", "unknown", ["protein powder"]),
];

export const NUTRITION = {
  chicken: nutrition("chicken breast", 165, 31, 0, 3.6, 120),
  turkey: nutrition("ground turkey", 170, 22, 0, 8, 120),
  eggs: nutrition("eggs", 143, 13, 1.1, 10, 50),
  greek_yogurt: nutrition("greek yogurt", 59, 10, 3.6, 0.4, 170),
  tofu: nutrition("tofu", 144, 17, 3, 9, 120),
  salmon: nutrition("salmon", 208, 20, 0, 13, 140),
  tuna: nutrition("tuna", 116, 26, 0, 1, 74),
  rice: nutrition("rice", 130, 2.7, 28, 0.3, 185),
  potatoes: nutrition("potatoes", 77, 2, 17, 0.1, 250),
  oats: nutrition("oats", 389, 16.9, 66, 6.9, 40),
  bread: nutrition("whole wheat bread", 247, 13, 41, 4.2, 38),
  tortillas: nutrition("whole wheat tortillas", 310, 9, 50, 8, 45),
  beans: nutrition("black beans", 132, 8.9, 24, 0.5, 130),
  lentils: nutrition("lentils", 116, 9, 20, 0.4, 140),
  broccoli: nutrition("broccoli", 35, 2.4, 7.2, 0.4, 120),
  spinach: nutrition("spinach", 23, 2.9, 3.6, 0.4, 85),
  banana: nutrition("banana", 89, 1.1, 23, 0.3, 118),
  berries: nutrition("berries", 57, 0.7, 14, 0.3, 140),
  olive_oil: nutrition("olive oil", 884, 0, 0, 100, 13),
  avocado: nutrition("avocado", 160, 2, 8.5, 14.7, 100),
  peanut_butter: nutrition("peanut butter", 588, 25, 20, 50, 32),
  protein_powder: nutrition("protein powder", 400, 80, 8, 6, 30),
};

export const MEAL_TEMPLATES = [
  {
    id: "protein_oats",
    name: "Protein oats bowl",
    mealType: "breakfast",
    tags: ["cheap", "quick", "high_protein"],
    slots: [
      slot("oats", ["oats"], 40, 100, 60),
      slot("protein", ["greek_yogurt", "protein_powder"], 20, 250, 170),
      slot("fruit", ["banana", "berries"], 50, 200, 100),
      slot("fat", ["peanut_butter"], 0, 40, 16),
    ],
    instructions: ["Mix oats with yogurt or protein powder.", "Top with fruit and peanut butter.", "Chill overnight or microwave oats first."],
  },
  {
    id: "rice_bowl",
    name: "Lean protein rice bowl",
    mealType: "lunch",
    tags: ["meal_prep", "balanced"],
    slots: [
      slot("protein", ["chicken", "turkey", "tofu", "salmon"], 100, 250, 170),
      slot("carb", ["rice", "potatoes"], 80, 350, 200),
      slot("vegetable", ["broccoli", "spinach"], 100, 300, 150),
      slot("fat", ["olive_oil", "avocado"], 0, 35, 10),
    ],
    instructions: ["Cook the protein with salt-free seasoning.", "Batch rice or potatoes.", "Portion vegetables and add fat after reheating."],
  },
  {
    id: "wrap_plate",
    name: "Turkey bean wrap plate",
    mealType: "dinner",
    tags: ["quick", "portable"],
    slots: [
      slot("protein", ["turkey", "tofu", "tuna"], 90, 220, 150),
      slot("carb", ["tortillas", "bread"], 50, 160, 90),
      slot("legume", ["beans", "lentils"], 70, 220, 130),
      slot("vegetable", ["spinach", "broccoli"], 60, 220, 100),
    ],
    instructions: ["Cook or warm the protein and legumes.", "Fill wraps with greens.", "Pack extra vegetables on the side."],
  },
  {
    id: "yogurt_snack",
    name: "Greek yogurt snack box",
    mealType: "snack",
    tags: ["no_cook", "high_protein"],
    slots: [
      slot("protein", ["greek_yogurt"], 120, 300, 200),
      slot("fruit", ["berries", "banana"], 50, 200, 100),
      slot("fat", ["peanut_butter"], 0, 32, 12),
    ],
    instructions: ["Portion yogurt into containers.", "Add fruit before eating.", "Keep peanut butter separate for texture."],
  },
];

function product(id, name, category, priceCents, sizeText, available, searchTerms) {
  return {
    provider: "mock",
    providerProductId: `mock-${id}`,
    storeId: "",
    upc: undefined,
    name,
    brand: "Mock Pantry",
    category,
    sizeText,
    packageQuantity: 1,
    priceCents,
    priceCurrency: "USD",
    available,
    fulfillment: { pickup: false, delivery: false, inStore: true },
    sourceUrl: undefined,
    searchTerms,
  };
}

function nutrition(ingredientName, caloriesKcal, proteinG, carbsG, fatG, servingSizeG) {
  return {
    ingredientName,
    matchedSource: "estimated",
    confidence: "medium",
    per100g: { caloriesKcal, proteinG, carbsG, fatG },
    servingSizeG,
    notes: "Offline prototype estimate. Replace with USDA/OpenFoodFacts in production.",
  };
}

function slot(slotName, allowedCategories, minGrams, maxGrams, defaultGrams) {
  return { slotName, allowedCategories, minGrams, maxGrams, defaultGrams };
}
